language: node_js
node_js: 5.5.0
install:
  - npm install -g npm@2.7.5
  - npm install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - gulp
